/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;


import zjni.demo.crash.example.Library;

public class LibraryCaller {

    public static void main(String[] args) throws NoSuchFieldException, IllegalAccessException {
        new Library().callAndCrash();
    }
}
