/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;


import jni.demo.crash.example.Library;

public class LibraryCaller {

    public static void main(String[] args) {
        new Library().callAndCrash();
    }
}
