/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zjni.demo.crash.example;

public class Library {
    static {

        try {
            System.loadLibrary("jni_demo_crash_example_Library");
        } catch (Exception e) {
            throw  new IllegalStateException("Cannot setup tets without jni_demo_crash_example 's dll");
        }
    }
    // just crash
    private native void crashJVM();

    public void callAndCrash () {
        new Library().crashJVM();
    }
}
